acll/config/routes.rb
Rails.application.routes.draw do
  get 'crews/index'

  get 'coaches/index'

  get 'sessions/new' => 'sessions#new'

  post 'sessions/create' => 'sessions#create'

  delete '/sessions' => 'sessions#destroy'

  get '/' => 'welcome#index'

  resources :leagues do 
  	resources :teams
  end

  resources :users do
  	resources :kids
  end
end

acll/app/models/kid.rb
class Kid < ActiveRecord::Base
	belongs_to :user
	belongs_to :team
end

acll/app/models/league.rb
class League < ActiveRecord::Base
	has_many :teams
end

acll/app/models/team.rb
class Team < ActiveRecord::Base
	belongs_to :league
	has_many :kids
end

acll/app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :kids

	def self.confirm(params)
        @user = User.find_by({email: params[:email]})
        @user.try(:authenticate, params[:password])
    end
end

acll/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include ApplicationHelper
  def authorize_admin
  	redirect_to "/", alert: 'Access Denied' unless current_user.is_admin?
  end
end

acll/app/controllers/coaches_controller.rb
class CoachesController < ApplicationController
  def index
  end
end

acll/app/controllers/crews_controller.rb
class CrewsController < ApplicationController
  def index
  end
end

acll/app/controllers/kids_controller.rb
class KidsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    if current_user == @user
      @kid = Kid.find_by_id(:id)
      @kid = Kid.all
    elsif current_user
      redirect_to user_kids_path(current_user.id)
    else
      redirect_to root_path
    end

  end

  def show
      @user = User.find(params[:user_id])
      id = params[:id]
      @kid = Kid.find(params[:id])
      @user = User.find_by_id(@kid.user_id)
      if current_user.id == @kid.id
        render :show
      else
        redirect_to root_path
      end
  end

  def new
    @kid = Kid.new
  end

  def create
      @kid = Kid.new(kid_params)
      @kid.user_id = current_user.id
      if @kid.save
          flash[:success] = "Welcome!"
          redirect_to("/users/#{@kid.user_id}")
      else
          flash[:danger] = "It failed!"
          render 'new'
      end
  end

  def edit
        @kid = Kid.find(params[:id])
        if current_user.id  == @kid.user_id
            render :edit
        else
            redirect_to root_path
        end
  end

  def update
    @kid = Kid.find(params[:id])    
        if @kid.update(kid_params)
          redirect_to user_kid_path
        else
          render :edit
        end
  end

  private

  def kid_params
    params.require(:kid).permit(:first_name, :last_name, :address, :city, :zip_code, :league, :coach, :user_id, :team_id, :guardian_first_name, :guardian_last_name)
  end
end

acll/app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  def index
    @leagues = League.all
  end

  def show
    id = params[:id]
    @league = League.find(params[:id])
  end

  def new
  end

  def create
    @league = League.new(league_params)
    if @league.save
        flash[:success] = "Welcome!"
        redirect_to leagues_path
    else
        flash[:danger] = "It failed!"
        render 'new'
    end
  end

  def edit
  end

  private

  def league_params
    params.require(:league).permit(:name)
  end
end

acll/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  	@user = User.new
  end

  def create
    @user = User.confirm(params)
    if @user
      login(@user)
      redirect_to user_path(@user.id)
    else
      flash[:danger] = "It failed!"
      redirect_to sessions_new_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to "/"
  end
 
private

  def user_params
    params.require(:user).permit(:email, :password)  
  end


end

acll/app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :authorize_admin, except: [:index, :show]
  def index
    @league = League.find(params[:league_id])
    #@team = Team.find(params[:id])
    @teams = Team.where(league_id: @league.id)
  end

  def show
    #@league = League.find(params[:league])
    #@kid = Kid.find(params[:kid_id])
    @team = Team.find(params[:id])
  end

  def new
    @league = League.find(params[:league_id])
    @team = Team.new
  end

  def create
      @league = League.find(params[:league_id])
      @team = Team.new(team_params)
      @team.league_id = @league.id
      # need logic for admin here
      if @team.save
          flash[:success] = "Welcome!"
          redirect_to("/leagues/#{@team.league_id}/teams")
      else
          flash[:danger] = "It failed!"
          render 'new'
      end
  end

  def edit
  end

    private

  def team_params
    params.require(:team).permit(:name, :coach1, :coach2, :coach3, :league_id)
  end
end

acll/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
      id = params[:id]

      @user = User.find(params[:id])
      if current_user.id == @user.id
        render :show
      else
        redirect_to root_path
      end
  end

  def new
    @user = User.new
  end

  def create
      @user = User.new(user_params)
      if @user.save
          login(@user)
          flash[:success] = "Welcome!"
          redirect_to("/users/#{@user.id}")
      else
          flash[:danger] = "It failed!"
          render 'new'
      end
  end

  def edit
      @user = User.find(params[:id])
      if current_user.id  == @user.id
          render :edit
      else
          redirect_to root_path
      end
  end

  def update
    @user = User.find(params[:id])    
        if @user.update(user_params)
          redirect_to user_path
        else
          render :edit
        end
  end

  def destroy
    id = params[:id]
    user = User.find(id)
    user.destroy
    redirect_to root_path
  end

private

  def user_params
    params.require(:user).permit(:email, :password, :first_name, :last_name)
  end
end

acll/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

acll/app/helpers/application_helper.rb
module ApplicationHelper
	include SessionsHelper
	include TeamsHelper
end

acll/app/helpers/coaches_helper.rb
module CoachesHelper
end

acll/app/helpers/crews_helper.rb
module CrewsHelper
end

acll/app/helpers/kids_helper.rb
module KidsHelper
end

acll/app/helpers/leagues_helper.rb
module LeaguesHelper
end

acll/app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    session[:user_id] = user.id
    @current_user = user
  end

  def logged_in?
    if @current_user == nil
      redirect_to "/sessions/new"
    end
  end

  def signed_in?
    if current_user == nil
      return false
    else
      return true
    end
  end

  def destroy
    @current_user = session[:user_id] = nil
  end

  private
  def current_user 
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

acll/app/helpers/teams_helper.rb
module TeamsHelper
  # private
  # def current_league 
  #   @current_league ||= League.find(session[:id]) if session[:id]
  # end
end

acll/app/helpers/users_helper.rb
module UsersHelper
end

acll/app/helpers/welcome_helper.rb
module WelcomeHelper
end

acll/app/views/coaches/index.html.erb
<h1>Coaches#index</h1>
<p>Find me in app/views/coaches/index.html.erb</p>

acll/app/views/crews/index.html.erb
<div class="bs-example" data-example-id="simple-table">
	<table class="table">
	  <thead>
	  	<tr>
	  		<th>Role</th>
	  		<th>Name</th>
	  		<th>Email</th>
	  	</tr>
	  </thead>
	  <tbody>
	  	<tr>
	  		<td>President</td>
	  		<td>Robert Cole</td>
	  		<td>president@amcanII.org</td>
	  	</tr>
	  </tbody>
	  <tbody>
	  	<tr>
	  		<td>Vice President</td>
	  		<td>Jamey Jackson</td>
	  		<td>vicepresident@amcanII.org</td>
	  	</tr>
	  </tbody>
	  <tbody>
	  	<tr>
	  		<td>Secretary</td>
	  		<td>Melissa Cole</td>
	  		<td>secretary@amcanII.org</td>
	  	</tr>
	  </tbody>
	  <tbody>
	  	<tr>
	  		<td>Canteen</td>
	  		<td>Christy Jackson</td>
	  		<td>canteen@amcanII.org</td>
	  	</tr>
	  </tbody>
	  <tbody>
	  	<tr>
	  		<td>Chief Umpire</td>
	  		<td>Everett Buyarski</td>
	  		<td>umpires@amcanII.org</td>
	  	</tr>
	  </tbody>
	  <tbody>
	  	<tr>
	  		<td>Player Agent 1</td>
	  		<td>Jeff Servente</td>
	  		<td>admin@amcanII.org</td>
	  	</tr>
	  </tbody>	  	  	  
	</table>
</div>

acll/app/views/kids/create.html.erb
<h1>Kids#create</h1>
<p>Find me in app/views/kids/create.html.erb</p>

acll/app/views/kids/edit.html.erb
<div class="container">
<h1 class="edit-performer-header">Edit Your Kid's Profile</h1>

<div class="col-md-8">

      <%= form_for @kid, url: user_kid_path do |f| %>
	    <div class="form-group">
	      <%= f.text_field :first_name, placeholder: 'First Name', class: "form-control" %>
	    </div>
	    <div class="form-group">
	      <%= f.text_field :last_name, placeholder: 'Last Name', class: "form-control" %>
	    </div>
	    <div class="form-group">
	      <%= f.text_field :dob, placeholder: 'MM/DD/YYYY', class: "form-control" %>
	    </div>
	    <div class="form-group">
	      <%= f.text_field :address, placeholder: 'Address', class: "form-control" %>
	    </div>
	    <div class="form-group">
	      <%= f.text_field :city, placeholder: 'City', class: "form-control" %>
	    </div>
	    <div class="form-group">
	      <%= f.number_field :zip_code, placeholder: 'Zip Code', class: "form-control" %>
	    </div>
	    <div class="form-group">
	      <%= f.text_field :guardian_first_name, placeholder: 'Guardian First Name', class: "form-control" %>
	    </div>
	    <div class="form-group">
	      <%= f.text_field :guardian_last_name, placeholder: 'Guardian Last Name', class: "form-control" %>
	    </div>
      <%= f.submit "Edit", class: "ghost-button" %>
</div>
<% end %>
</div>

acll/app/views/kids/index.html.erb
<h1>Your Kids</h1>
<% @kid.each do |k| %>
	<div class='col-sm-10 col-md-8'>
		<%= link_to k.first_name, user_kid_path(@user,k), method: :get %>
	</div>
	<%end%>

acll/app/views/kids/new.html.erb
<h1>Signup Your Kid!</h1> 
    <%= form_for @kid, url: user_kids_path do |f| %> 
	    <div class="form-group">
	      <%= f.text_field :first_name, placeholder: 'First Name', class: "form-control", required: true %>
	    </div>
	    <div class="form-group">
	      <%= f.text_field :last_name, placeholder: 'Last Name', class: "form-control", required: true %>
	    </div>
	    <div class="form-group">
	      <%= f.text_field :dob, placeholder: 'MM/DD/YYYY', class: "form-control", required: true %>
	    </div>
	    <div class="form-group">
	      <%= f.text_field :address, placeholder: 'Address', class: "form-control", required: true %>
	    </div>
	    <div class="form-group">
	      <%= f.text_field :city, placeholder: 'City', class: "form-control", required: true %>
	    </div>
	    <div class="form-group">
	      <%= f.number_field :zip_code, placeholder: 'Zip Code', class: "form-control", required: true %>
	    </div>
	    <div class="form-group">
	      <%= f.text_field :guardian_first_name, placeholder: 'Guardian First Name', class: "form-control", required: true %>
	    </div>
	    <div class="form-group">
	      <%= f.text_field :guardian_last_name, placeholder: 'Guardian Last Name', class: "form-control", required: true %>
	    </div>
	    <%= f.submit "Signup!", class: "ghost-button" %>
 	<% end %>

acll/app/views/kids/show.html.erb
<h3><%= @kid.first_name %> </h3>
<h3><%= @kid.last_name %> </h3>
<h3><%= @kid.address %> </h3>
<h3><%= @kid.zip_code %> </h3>
<h3><%= @kid.dob %> </h3>
<h3><%= @kid.guardian_first_name %> </h3>
<h3><%= @kid.guardian_last_name %> </h3>
<%= button_to "Edit Information!", edit_user_kid_path(@user,@kid), method: :get, class: "btn btn-default text-center" %>

acll/app/views/leagues/create.html.erb
<h1>Leagues#create</h1>
<p>Find me in app/views/leagues/create.html.erb</p>

acll/app/views/leagues/edit.html.erb
<h1>Leagues#edit</h1>
<p>Find me in app/views/leagues/edit.html.erb</p>

acll/app/views/leagues/index.html.erb
<h1>Leagues</h1>
	<% @leagues.each do |l| %>
		<div class='col-sm-10 col-md-8'>
			<%= link_to l.name, league_teams_path(l), method: :get %>
		</div>
	<% end %>

acll/app/views/leagues/new.html.erb
<h1>Leagues#new</h1>
<p>Find me in app/views/leagues/new.html.erb</p>

acll/app/views/leagues/show.html.erb
<h1><%= @league.name %></h1>
<!-- need logic for admin here -->
<%= button_to "Create Team Here", new_league_team_path(@league), method: :get, class: "btn btn-default text-center" %>

acll/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

acll/app/views/users/edit.html.erb
<div class="container">
<h1 class="edit-performer-header">Edit Your Settings</h1>

<div class="col-md-8">

      <%= form_for @user do |f| %>
	    <div class="form-group">
	      <%= f.email_field :email, placeholder: 'Email', class: "form-control" %>
	    </div>
	    <div class="form-group">
	      <%= f.password_field :password, placeholder: 'Password', class: "form-control" %>
	    </div>
	    <div class="form-group">
	      <%= f.text_field :first_name, placeholder: 'First Name', class: "form-control" %>
	    </div>
	    <div class="form-group">
	      <%= f.text_field :last_name, placeholder: 'Last Name', class: "form-control" %>
	    </div>
      <%= f.submit "Edit", class: "ghost-button" %>
</div>
<% end %>
</div>

acll/app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

acll/app/views/users/new.html.erb
<h1> Signup Here! </h1>    
    <%= form_for @user do |f| %> 
	    <div class="form-group">
	      <%= f.email_field :email, placeholder: 'Email', class: "form-control", required: true %>
	    </div>
	    <div class="form-group">
	      <%= f.password_field :password, placeholder: 'Password', class: "form-control", required: true %>
	    </div>
	    <div class="form-group">
	      <%= f.text_field :first_name, placeholder: 'First Name', class: "form-control", required: true %>
	    </div>
	    <div class="form-group">
	      <%= f.text_field :last_name, placeholder: 'Last Name', class: "form-control", required: true %>
	    </div>
	    <%= f.submit "Signup!", class: "ghost-button" %>
 	<% end %>

acll/app/views/users/show.html.erb
<h1>Welcome, <%= @user.first_name %>!</h1>
  <div class="text-center">
    <%= button_to "Signup Your Kid!", new_user_kid_path(@user), method: :get, class: "btn btn-default text-center" %>
    <%= button_to "View Signed Up Kids", user_kids_path(@user), method: :get, class: "btn btn-default text-center" %>
    <%= button_to "Edit Settings", edit_user_path, method: :get, class: "btn btn-default text-center" %>
  </div>

acll/app/views/welcome/index.html.erb
<h1> American Canyon Little League </h1>