acll/config/routes.rb
Rails.application.routes.draw do
  get 'crews/index'

  get 'coaches/index'

  get 'sessions/new' => 'sessions#new'

  post 'sessions/create' => 'sessions#create'

  delete '/sessions' => 'sessions#destroy'

  get '/' => 'welcome#index'

  resources :leagues do 
  	resources :teams
  end

  resources :users do
  	resources :kids
  end
end

acll/app/models/kid.rb
class Kid < ActiveRecord::Base
	belongs_to :user
	belongs_to :team
end

acll/app/models/league.rb
class League < ActiveRecord::Base
	has_many :teams
end

acll/app/models/team.rb
class Team < ActiveRecord::Base
	belongs_to :league
	has_many :kids
end

acll/app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :kids

	def self.confirm(params)
        @user = User.find_by({email: params[:email]})
        @user.try(:authenticate, params[:password])
    end
end

acll/app/controllers/coaches_controller.rb
class CoachesController < ApplicationController
  def index
  end
end

acll/app/controllers/crews_controller.rb
class CrewsController < ApplicationController
  def index
  end
end

acll/app/controllers/kids_controller.rb
class KidsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    if current_user == @user
      @kid = Kid.find_by_id(:id)
      @kid = Kid.all
    elsif current_user
      redirect_to user_kids_path(current_user.id)
    else
      redirect_to root_path
    end

  end

  def show
      @user = User.find(params[:user_id])
      id = params[:id]
      @kid = Kid.find(params[:id])
      @user = User.find_by_id(@kid.user_id)
      if current_user.id == @kid.id
        render :show
      else
        redirect_to root_path
      end
  end

  def new
    @kid = Kid.new
  end

  def create
      @kid = Kid.new(kid_params)
      @kid.user_id = current_user.id
      if @kid.save
          flash[:success] = "Welcome!"
          redirect_to("/users/#{@kid.user_id}")
      else
          flash[:danger] = "It failed!"
          render 'new'
      end
  end

  def edit
        @kid = Kid.find(params[:id])
        if current_user.id  == @kid.user_id
            render :edit
        else
            redirect_to root_path
        end
  end

  def update
    @kid = Kid.find(params[:id])    
        if @kid.update(kid_params)
          redirect_to user_kid_path
        else
          render :edit
        end
  end

  private

  def kid_params
    params.require(:kid).permit(:first_name, :last_name, :address, :city, :zip_code, :league, :coach, :user_id, :team_id, :guardian_first_name, :guardian_last_name)
  end
end

acll/app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  def index
    @leagues = League.all
  end

  def show
    id = params[:id]
    @league = League.find(params[:id])
  end

  def new
  end

  def create
    @league = League.new(league_params)
    if @league.save
        flash[:success] = "Welcome!"
        redirect_to leagues_path
    else
        flash[:danger] = "It failed!"
        render 'new'
    end
  end

  def edit
  end

  private

  def league_params
    params.require(:league).permit(:name)
  end
end

acll/app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :authorize_admin, except: [:index, :show]
  def index
    @league = League.find(params[:league_id])
    #@team = Team.find(params[:id])
    @teams = Team.where(league_id: @league.id)
  end

  def show
    #@league = League.find(params[:league])
    #@kid = Kid.find(params[:kid_id])
    @team = Team.find(params[:id])
  end

  def new
    @league = League.find(params[:league_id])
    @team = Team.new
  end

  def create
      @league = League.find(params[:league_id])
      @team = Team.new(team_params)
      @team.league_id = @league.id
      # need logic for admin here
      if @team.save
          flash[:success] = "Welcome!"
          redirect_to("/leagues/#{@team.league_id}/teams")
      else
          flash[:danger] = "It failed!"
          render 'new'
      end
  end

  def edit
  end

    private

  def team_params
    params.require(:team).permit(:name, :coach1, :coach2, :coach3, :league_id)
  end
end

acll/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
      id = params[:id]

      @user = User.find(params[:id])
      if current_user.id == @user.id
        render :show
      else
        redirect_to root_path
      end
  end

  def new
    @user = User.new
  end

  def create
      @user = User.new(user_params)
      if @user.save
          login(@user)
          flash[:success] = "Welcome!"
          redirect_to("/users/#{@user.id}")
      else
          flash[:danger] = "It failed!"
          render 'new'
      end
  end

  def edit
      @user = User.find(params[:id])
      if current_user.id  == @user.id
          render :edit
      else
          redirect_to root_path
      end
  end

  def update
    @user = User.find(params[:id])    
        if @user.update(user_params)
          redirect_to user_path
        else
          render :edit
        end
  end

  def destroy
    id = params[:id]
    user = User.find(id)
    user.destroy
    redirect_to root_path
  end

private

  def user_params
    params.require(:user).permit(:email, :password, :first_name, :last_name)
  end
end

acll/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

acll/app/helpers/application_helper.rb
module ApplicationHelper
	include SessionsHelper
	include TeamsHelper
end

acll/app/helpers/coaches_helper.rb
module CoachesHelper
end

acll/app/helpers/crews_helper.rb
module CrewsHelper
end

acll/app/helpers/kids_helper.rb
module KidsHelper
end

acll/app/helpers/leagues_helper.rb
module LeaguesHelper
end

acll/app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    session[:user_id] = user.id
    @current_user = user
  end

  def logged_in?
    if @current_user == nil
      redirect_to "/sessions/new"
    end
  end

  def signed_in?
    if current_user == nil
      return false
    else
      return true
    end
  end

  def destroy
    @current_user = session[:user_id] = nil
  end

  private
  def current_user 
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

acll/app/helpers/teams_helper.rb
module TeamsHelper
  # private
  # def current_league 
  #   @current_league ||= League.find(session[:id]) if session[:id]
  # end
end

acll/app/helpers/users_helper.rb
module UsersHelper
end

acll/app/helpers/welcome_helper.rb
module WelcomeHelper
end

acll/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Acll</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "partials/navbar" %>

<%= yield %>

</body>
</html>

acll/app/views/partials/_navbar.html.erb
	<nav class="navbar navbar-default">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="#"></a>
	    </div>
	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">

	      	<li><%= link_to "Home", "/", class: "nav-text" %></li>
	      	<li><%= link_to "Leagues", leagues_path, class: "nav-text" %></li>
	      	<li><%= link_to "Board", crews_index_path, class: "nav-text" %></li>
	      		<% if current_user %>
	      			<li><%= link_to "Profile", user_path(current_user.id), class: "nav-text" %></li>
	      			<li><%= link_to "Log Out", sessions_path, method: :delete, class: "nav-text" %></li>
	      		<% else %>
					<li><%= link_to "Signup", new_user_path, class: "nav-text" %></li>
					<li><%= link_to "Login", sessions_new_path, class: "nav-text" %></li>
				<% end %>
	      </ul>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>